@host=https://localhost:7244
GET {{host}}/dinner
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0M2MyYWE3ZS1mYTAzLTRlYzQtODE0Zi1hODEyOTYzMzlmNTIiLCJnaXZlbl9uYW1lIjoiVGhhbmgiLCJmYW1pbHlfbmFtZSI6IkxlIiwianRpIjoiYjRjODg1M2YtZGY4ZS00ZDE5LTlmMTctZjI4NjViYzkyNDE0IiwiZXhwIjoxNzE2OTU0NzExLCJpc3MiOiJEaW5uZXJEREQiLCJhdWQiOiJEaW5uZXJEREQifQ.G8g4b-iUXfJcayjreqIQ3GApfY0S9O4Xf5j3Pd-lVU0
